### ISSUE TITLE
Description du produit

### ISSUE THREAD

**Issue by Chateux** [skyflow-io/npm-skyflow-cli#1]
Description du produit non explicite...
J'entends par là, que nous comprenons pas le but concret du produit et de quoi il en convient.

**Comment by Yoann-Vie** [comment]
Nous avons mis à jour le readme du projet et créer des documentations annexes pour : 
- la configuration : https://github.com/skyflow-io/npm-skyflow-cli/blob/master/doc/CONFIG.md
