### ISSUE TITLE
Problem avec le Module React  

### ISSUE THREAD

**Issue by nicolasdet** [skyflow-io/npm-skyflow-cli#4]
### Environenement

Windows 10 - docker toolbox

J'utilise Yarn mais j'ai eux les même problème avec npm 

### Issue 

Lorsque je Build React avec npm run-script build   OU yarn build  j'ai une erreur : 

### résumer des étapes pour arriver au bug :

ps: j'ai deja yarn et npm installer en global. 

![error2](https://user-images.githubusercontent.com/13063865/45367604-ef307700-b5e1-11e8-93ad-e703dbb4a60e.png)

J'installe les package (car il à pas réussit au dessus comme on peut le voir sur le screen) mais jusque la tout va bien : 

![error2-1](https://user-images.githubusercontent.com/13063865/45367666-12f3bd00-b5e2-11e8-860b-40f790c716fd.png)

Je build l'application et la Alerte : 

![error2-2](https://user-images.githubusercontent.com/13063865/45367721-2ef75e80-b5e2-11e8-9cfd-98643b5b4664.png)

**Comment by franckdiomande** [comment]
Nice! It's fixed
