### ISSUE TITLE
chmod 777 usage

### ISSUE THREAD

**Issue by angristan** [skyflow-io/npm-skyflow-cli#8]
There is about 30 `shx.chmod(777, filename);` in the module. 

This is considered bad practice, so is it really needed?

**Comment by franckdiomande** [comment]
We have encountered many problems on different operating systems. For simplicity, we make files accessible in development mode. Skyflow is open source and we are looking for developers to help us.

**Comment by angristan** [comment]
I understand, did these issues happen with `775` by any chance?

**Comment by franckdiomande** [comment]
This issue happened on a debian system with 775
